const assert = require('node:assert/strict');
const fs = require('node:fs');
const { readJavaScriptSources } = require('./helpers/source-utils');

const jsSource = readJavaScriptSources('assets/js');
const cssSource = fs.readFileSync('assets/css/styles.css', 'utf8');
const configSource = fs.readFileSync('config.yml', 'utf8');
const indexSource = fs.readFileSync('index.html', 'utf8');

[
  'assets/js/features/character-sheet/character-sheet-actions.js',
  'assets/js/features/character-sheet/character-sheet-backup.js',
  'assets/js/features/character-sheet/character-sheet-classes.js',
  'assets/js/features/character-sheet/character-sheet-combat-renderer.js',
  'assets/js/features/character-sheet/character-sheet-events.js',
  'assets/js/features/character-sheet/character-sheet-fields.js',
  'assets/js/features/character-sheet/character-sheet-inventory-renderer.js',
  'assets/js/features/character-sheet/character-sheet-normalizers.js',
  'assets/js/features/character-sheet/character-sheet-overview-renderer.js',
  'assets/js/features/character-sheet/character-sheet-renderers.js',
  'assets/js/features/character-sheet/character-sheet-spells-renderer.js',
  'assets/js/features/character-sheet/character-sheet-storage.js',
  'assets/js/features/character-sheet/character-sheet-view.js',
  'assets/js/reference-section-renderer.js',
].forEach((file) => assert.ok(fs.existsSync(file), `${file} deve esistere`));

[
  "character_sheet: []",
  "character_sheet: {",
  "type: 'tool'",
  "export const CHARACTER_SHEET_STORAGE_KEY = 'dnd-reference:character-sheet';",
  "export const CHARACTER_SHEETS_STORAGE_KEY = 'dnd-reference:character-sheets';",
  "export const ACTIVE_CHARACTER_SHEET_STORAGE_KEY = 'dnd-reference:active-character-sheet';",
  "export const APP_STORAGE_PREFIX = 'dnd-reference:';",
  'const CHARACTER_SHEET_SCHEMA_VERSION = 9;',
  'const SKILL_META = [',
  "id: ''",
  'schemaVersion: CHARACTER_SHEET_SCHEMA_VERSION',
  'createCharacterSheetActionsController',
  'createCharacterSheetBackupController',
  'createCharacterSheetClassController',
  'createCharacterSheetEventsController',
  'createCharacterSheetRenderer',
  'normalizeCharacterSheet',
  'normalizeCharacterSheetArchive',
  "'Ire', 'Ira'",
  "'Imposizione delle mani'",
  "'Concentrazione', 'Punti concentrazione'",
  "'Slot incantesimo', 'Slot patto'",
  'skillProficiencies: Object.fromEntries(SKILL_META.map(([key]) => [key, 0]))',
  'proficiencies: {',
  'resources: []',
  'status: {',
  'attacks: []',
  'spellSlotsUsed: {}',
  'magicItems: []',
  'attunedMagicItems: []',
  'data-sheet-add-attack',
  'data-sheet-attack-field',
  'data-sheet-remove-attack',
  'data-sheet-skill',
  'data-sheet-suggest-skill',
  'data-sheet-proficiency',
  'data-sheet-add-resource',
  'data-sheet-resource-field',
  'data-sheet-resource-delta',
  'data-sheet-reset-resources',
  'data-sheet-remove-resource',
  'data-sheet-status-check',
  'data-sheet-status-number',
  'data-sheet-status-field',
  'syncCharacterSheetClassResources();',
  'Import archivio schede',
  'Unisci',
  'data-sheet-add-condition',
  'data-sheet-remove-condition',
  'data-sheet-switch-character',
  'data-sheet-duplicate',
  'data-sheet-export-archive',
  'data-sheet-import-archive',
  'data-sheet-import-archive-mode',
  'data-sheet-import-archive-cancel',
  'data-app-export-backup',
  'data-app-import-backup',
  'data-app-import-backup-apply',
  'data-app-import-backup-cancel',
  'app-backup-import',
  'character-sheet-archive-import',
  'data-sheet-delete',
  'data-sheet-use-class',
  'data-sheet-add-detail-spell',
  'data-sheet-add-magic-item',
  'data-sheet-remove-magic-item',
  'data-sheet-toggle-attunement',
  'data-sheet-add-spell',
  'data-sheet-slot-delta',
  'data-sheet-reset-spell-slots',
  'data-dice-roll="${escapeAttr(rollFormula(20, modifier))}"',
  'window.DndReferenceTest',
].forEach((token) => assert.ok(jsSource.includes(token), `${token} deve essere presente nei sorgenti JS`));

[
  '.character-sheet',
  '.sheet-manager',
  '.sheet-character-picker',
  '.sheet-character-select',
  '.sheet-more-actions',
  '.sheet-archive-confirm',
  '.sheet-archive-actions',
  '.sheet-danger-action',
  '.sheet-tabs',
  '.sheet-actions',
  '.skill-grid',
  '.skill-suggestions',
  '.skill-control',
  '.sheet-proficiency-grid',
  '.sheet-status',
  '.sheet-condition',
  '.sheet-resource-form',
  '.sheet-resource-toolbar',
  '.sheet-resource-edit',
  '.sheet-resource',
  '.sheet-spell-grid',
  '.sheet-spell-picker',
  '.sheet-attack-form',
  '.sheet-attack-edit',
  '.sheet-attack',
  '.sheet-attunement',
  '.sheet-item-actions',
  '.sheet-slot-grid',
  '.sheet-slot-toolbar',
  '.sheet-slot',
  '.sheet-slot-actions',
  '.sheet-level-summary',
  '.ability-grid',
  '.sheet-class-summary',
  '.sheet-chip-list',
  '.prepared-spell',
  '.sheet-item',
  'scroll-snap-type: x proximity',
  'font-size: 16px',
].forEach((token) => assert.ok(cssSource.includes(token), `${token} deve essere presente nel CSS`));

assert.match(configSource, /character_sheet: Scheda/);
assert.match(indexSource, /20260514-attack-editor/);
assert.doesNotMatch(jsSource, /localStorage\.setItem\('dnd5'/);
assert.doesNotMatch(jsSource, /localStorage\.setItem\('dnd-theme'/);

console.log('Scheda personaggio OK');
